sudo: false
language: generic

services:
  - postgresql

env:
  matrix:
    - STACK_YAML=stack.yaml
# allow_failures:
#   - GHCVER=8.4  STACK_YAML=stack-8.4.yaml

install:
  # Stack installation
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --no-terminal --version

before_script:
  - psql -c "create user travis with password 'password'" -U postgres
  - psql -c 'create database scheduler_test;' -U postgres
  - psql -c 'grant all privileges on database scheduler_test to travis' -U postgres

script:
  - stack setup --no-terminal
  - stack update --no-terminal
  # -j2 has been about right on TravisCI IME
  - stack build -j2 --fast --no-terminal
  # You might want to remove --fast if you want to
  # upload optimized binaries on a successful build
  - stack test --fast --no-terminal

after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls [options] [test-suite-names]

cache:
  timeout: 2000
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.stack
  - .stack-work/
  apt: true
