sudo: false
language: generic
services:
- postgresql
env:
  matrix:
  - GHCVER=8.8.4 STACK_YAML=stack.yaml
install:
- mkdir -p ~/.local/bin
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v2.5.1/stack-2.5.1-linux-x86_64.tar.gz
  | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- export PATH=~/.local/bin:$PATH
- stack --no-terminal --version
before_script:
- psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='travis'" | grep -q 1 ||
  psql -c "create user travis with password 'password'" -U postgres
- psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'scheduler_test'"
  | grep -q 1 || psql -c 'create database scheduler_test;' -U postgres
- psql -c 'grant all privileges on database scheduler_test to travis' -U postgres
script:
- stack setup --no-terminal
- stack update --no-terminal
- stack build -j2 --fast --no-terminal
- stack test --coverage --fast --no-terminal
after_script:
- travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2
  | tar -xj
- "./shc scheduler scheduler-test"
cache:
  timeout: 2000
  directories:
  - "$HOME/.cabal"
  - "$HOME/.ghc"
  - "$HOME/.stack"
  - ".stack-work/"
  apt: true
deploy:
  provider: heroku
  api_key:
    secure: kcUtCdA6oVSH07hY/NDakLDhwwcpiBmHnzP10sH8+3RsdyFCI+9rI8kum8iobzeww/uyXbvyw2XQoTCy18fEVcmsLLYL6d6DOKzDwr1Kpe5VvscDsbMMGuq/V+ESIV1Q3cBTIcCWO51vTdnGVPtZP5CckYwGUONVItM578efekg3AtoAAkaULHFrFayibL/HFAg9Vu1m/LlXgdeyi4ogXumik6y7H++4tseNSNFbFvWdQj265S5qlGisaxsx4FhyF5m49c+Ch0bfwG2TiYZVBad+Brz8ceyrrfaT5urS1r6RVEqF9JXQGCTy/7rR1/P8h4C4Ef9eeEsm2SiqODwX3Cq1qljLsWkv8U8FwLTfiKUM9jIQq4GhWADpihgw2fbhYyZRzNPwLLLjXmfH7HoFzZ0l8w6NPOPeA1M2AXjydCbzabOXJKfRCOTuwLxikSefZjzo1mmYZIr0JoRVOGrT7CT3f3L4kpRM6gidx2rCuolROqxGWlIgymzGpcVXZw39tCBhlQ48qFIkUZiatl3VtdjYjrei6q/ZKCO/B2qT6ZYEvnKRIPZIINx8F+oh0g70vsXtJNZWOQKfi1NXtqxu2X08VuPUxL9aSXjRtVPFBiPdOyIKHNb9lvAK4xqOmojTyI1GoSz5T2kCq+u+6uLiBMMuPw5S2qRDFLVVEFgKgYo=
  app: todosprint
  on:
    repo: travv0/todosprint
