sudo: false
language: generic
services:
- postgresql
env:
  matrix:
  - GHCVER=8.8.4 STACK_YAML=stack.yaml
install:
- mkdir -p ~/.local/bin
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v2.5.1/stack-2.5.1-linux-x86_64.tar.gz
  | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- export PATH=~/.local/bin:$PATH
- stack --no-terminal --version
before_script:
- psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='travis'" | grep -q 1 ||
  psql -c "create user travis with password 'password'" -U postgres
- psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'scheduler_test'"
  | grep -q 1 || psql -c 'create database scheduler_test;' -U postgres
- psql -c 'grant all privileges on database scheduler_test to travis' -U postgres
script:
- stack setup --no-terminal
- stack update --no-terminal
- stack build -j2 --fast --no-terminal --ghc-options '-Werror'
- stack test --coverage --fast --no-terminal --ghc-options '-Werror'
after_script:
- travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2
  | tar -xj
- "./shc scheduler scheduler-test"
cache:
  timeout: 2000
  directories:
  - "$HOME/.cabal"
  - "$HOME/.ghc"
  - "$HOME/.stack"
  - ".stack-work/"
  apt: true
deploy:
  provider: heroku
  api_key:
    secure: 1In+e6iQ/qiiMTzVGRlDIZVTpmZ6s/6oV5Pzhaj02OpjnpprEr3NzkvmwrmjuyMY+3wOghOIitn1uAc4g1mGmQoPU3xLatP9q7SkIo0YQPJbWMFI3fsuHPkrzvga91vlM9Y62JnD2zzumX+EsBVLjIEbMX3EPkp1akhnZQ0BI7iXUvUGOWUGerzEYkjggTGcO1WJoLHUI+FzJGNcFvxJp3bpnejLLmNYzF1HXH7oZWOjtxksV4nbqqRhErLxINArtfrTg7EdIM4TE63I6kEuQJGGwIsD02P2esu51MW9d3fayf+HWlDfDMAhJ0N7xe6Dr3amZIiyk7B7X5XeILTkRHF/Dk+uhJ6u4hTqhBkmWPq6aLZoSaAXvHfxwcOIlhQm2DDxyFdQYCbc9RU1TEKA/enSfM6QPvV0iqPkC1auW+XaWLLRX+xrn5cK/cT565S+Hm8GbJHVHKhZXJV5KRBU0MMD4/ko9Fi1Oxq0IJ7E9zn3ELZ2tZNwy9w261ru93Z4nM90AX8wD6AsOZh/gTuVJQqL32QCdUT9+wHPQQvMavLfJdvR3MMaNV/oZ0kO5zcpeYNupMb88YRHfhSGlj88vK2pcZi+hPcPijLX9RzsQg6uM3P84Fgd3zIil/qUSppZx1dvktnnoBn4Jwn+y3Hh1htWQgNiIJElTwlhRBxCAS0=
  app: todosprint
  on:
    repo: travv0/todosprint
