name:    scheduler
version: "0.0.0"

dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5

- aeson 
- case-insensitive
- classy-prelude 
- classy-prelude-yesod 
- fast-logger 
- file-embed
- foreign-store
- hjsmin 
- monad-logger 
- persistent 
- persistent-postgresql 
- persistent-template 
- shakespeare 
- template-haskell
- text 
- time
- wai
- wai-extra 
- warp 
- yaml 
- yesod 
- yesod-auth 
- yesod-auth-oauth2
- yesod-core 
- yesod-form 
- yesod-static 

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns

# Runnable executable for our application
executables:
  scheduler:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scheduler
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  scheduler-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - scheduler
    - hspec >=2.0.0
    - yesod-test

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
